# Generated by Django 4.1.1 on 2022-10-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="username", new_name="author",
        ),
    ]
